on:
  push:
    branches:
      - main
      - ci-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: xu-cheng/texlive-action@v2
      with:
        texlive_version: 2023
        scheme: full
        run: ./mk
